### ISSUE TITLE
Server crashes if I use the 2.0.3 version.

### ISSUE THREAD

**Issue by ghost** [AlexLew95/GameAPI#8]
Hi, I tried to use the 2.0.3 GameAPI version for Skript, but when I started up the server, I tried to reload my Skript, but gived me many console errors. I removed the GameAPI and the problem is solved, but I can't create my minigame without him.

Sorry for bad english.
Skript version -> 2.2-dev36
Spigot version -> 1.8.8

Error
```
_**[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! [Skript] Severe Error:
[08:45:08 ERROR]: #!#! Could not load Core.sk
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! Something went horribly wrong with Skript.
[08:45:08 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:45:08 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[08:45:08 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[08:45:08 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[08:45:08 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[08:45:08 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! Stack trace:
[08:45:08 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for point
[08:45:08 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:814)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1535)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:662)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:331)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:361)
[08:45:08 ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:490)
[08:45:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[08:45:08 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[08:45:08 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[08:45:08 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[08:45:08 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:45:08 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:45:08 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! Version Information:
[08:45:08 ERROR]: #!#!   Skript: 2.2-dev36
[08:45:08 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[08:45:08 ERROR]: #!#!   Minecraft: 1.8.8
[08:45:08 ERROR]: #!#!   Java: 1.8.0_221 (Java HotSpot(TM) 64-Bit Server VM 25.221-b11)
[08:45:08 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! Server platform: Spigot
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! Current node: set time to 7:00 (Core.sk, line 2)
[08:45:08 ERROR]: #!#! Current item: null
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! Thread: Server thread
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! Language: english
[08:45:08 ERROR]: #!#! Link parse mode: DISABLED
[08:45:08 ERROR]: #!#!
[08:45:08 ERROR]: #!#! End of Error.
[08:45:08 ERROR]: #!#!
[08:45:08 INFO]: [Skript] All scripts loaded without errors.
[08:45:08 INFO]: [Skript] Loaded 2 scripts with a total of 0 triggers and 0 commands in 0.08 seconds
[08:45:08 INFO]: [Skript] Finished loading.
[08:45:08 INFO]: [HolographicDisplays] Found a new version available: v2.4.0
[08:45:08 INFO]: [HolographicDisplays] Download it on Bukkit Dev:
[08:45:08 INFO]: [HolographicDisplays] dev.bukkit.org/bukkit-plugins/holographic-displays
>,
[08:45:09 INFO]: (FAWE) Detected class org.bukkit.event.block.BlockExplodeEvent
[08:45:09 INFO]: Comando nÒo encontrado.
[08:45:09 INFO]: [TuSKe] Checking for latest update...
[08:45:09 INFO]: (FAWE) Super Pickaxe enabled.
[08:45:10 INFO]: [TuSKe] No new update was found!
[08:45:12 INFO]: [TuSKe] Generating documentation of Skript & Addons.
[08:45:13 INFO]: [TuSKe] Documentation was generated successfully.
>sk reload
[08:45:14 INFO]: Usage: /skript reload ...
[08:45:14 INFO]:   all - Reloads all configs and all scripts
[08:45:14 INFO]:   config - Reloads the main config
[08:45:14 INFO]:   aliases - Reloads the aliases configs (aliases-*.sk)
[08:45:14 INFO]:   scripts - Reloads all scripts
[08:45:14 INFO]:   <script> - Reloads a specific script or a folder of scripts
>sk reload Core
[08:45:15 INFO]: [Skript] Reloading Core.sk...
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! [Skript] Severe Error:
[08:45:15 ERROR]: #!#! Could not load Core.sk
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! Something went horribly wrong with Skript.
[08:45:15 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:45:15 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
[08:45:15 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
[08:45:15 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
[08:45:15 ERROR]: #!#! nor it will work, unless you switch to supported platform.
[08:45:15 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! Stack trace:
[08:45:15 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for point
[08:45:15 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:814)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1535)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:662)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:434)
[08:45:15 ERROR]: #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[08:45:15 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:45:15 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[08:45:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[08:45:15 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[08:45:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[08:45:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[08:45:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[08:45:15 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[08:45:15 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! Version Information:
[08:45:15 ERROR]: #!#!   Skript: 2.2-dev36
[08:45:15 ERROR]: #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
[08:45:15 ERROR]: #!#!   Minecraft: 1.8.8
[08:45:15 ERROR]: #!#!   Java: 1.8.0_221 (Java HotSpot(TM) 64-Bit Server VM 25.221-b11)
[08:45:15 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! Server platform: Spigot
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! Current node: set time to 7:00 (Core.sk, line 2)
[08:45:15 ERROR]: #!#! Current item: null
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! Thread: Server thread
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! Language: english
[08:45:15 ERROR]: #!#! Link parse mode: DISABLED
[08:45:15 ERROR]: #!#!
[08:45:15 ERROR]: #!#! End of Error.
[08:45:15 ERROR]: #!#!
[08:45:15 INFO]: [Skript] Successfully reloaded Core.sk.**_
```

**Comment by Olyno** [comment]
Hi, thanks for the report. I will fix this issue soon.

**Comment by Olyno** [comment]
Can you try this version for me please? https://bitbucket.org/Olyno/gameapi/downloads/gameapi-2.0.4-all.jar
If this versions works, it means I already fixed the issue a long time ago and should make a release of it.

**Comment by ghost** [comment]
It's giving me the same error :/

Olyno <notifications@github.com> escreveu no dia domingo, 6/10/2019 à(s)
22:45:

**Comment by ghost** [comment]
[23:08:52 ERROR]: #!#! Stack trace:
[23:08:52 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info
found for point
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1804)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1771)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1519)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:495)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:814)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1535)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:225)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:180)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.lang.Statement.parse(Statement.java:59)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:972)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:662)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:389)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:401)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:434)
[23:08:52 ERROR]: #!#!     at
ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:181)
[23:08:52 ERROR]: #!#!     at
org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:08:52 ERROR]: #!#!     at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[23:08:52 ERROR]: #!#!     at
org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[23:08:52 ERROR]: #!#!     at
org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[23:08:52 ERROR]: #!#!     at
net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[23:08:52 ERROR]: #!#!     at
net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[23:08:52 ERROR]: #!#!     at
net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[23:08:52 ERROR]: #!#!     at
net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[23:08:52 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)

Olyno <notifications@github.com> escreveu no dia domingo, 6/10/2019 à(s)
22:45:

**Comment by Olyno** [comment]
@nekkan did you solve this issue?

**Comment by ghost** [comment]
I don't use Skript anymore.

Olyno <notifications@github.com> escreveu no dia sábado, 9/11/2019 à(s)
21:55:
